@root=http://localhost:5000/api

GET {{root}}/data/flaky
Accept: application/json

###

GET http://localhost:5000/api/customers?v=1.0
Accept: application/json

###

GET http://localhost:5000/api/customers/9
Accept: application/vnd.design.rest-v2+json
#X-Version: 2.0


###
