@root=http://localhost:5000/api

GET {{root}}/data/flaky
Accept: application/json

###

GET http://localhost:5000/api/customers
Accept: application/json

###

GET {{root}}/regions 
Accept: application/json

###

GET {{root}}/sites
Accept: application/json

###

GET {{root}}/sites/1457 
Accept: application/json
